### ISSUE TITLE
Define "open development"

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy-v2.0-paper#140]
The referee says

> The phase 'open development' is used a few times but isn't really defined or connected to the broader open source ecosystem. What other communities are working in this way? How novel is 'open development' by their assessment? For example, other communities have adopted policies that encourage community contribution - most notable is the Node.js Foundation's contribution policies designed to promote 'Healthy Open Source' https://medium.com/the-node-js-collection/healthy-open-source-967fa8be7951 . How does the Astropy community efforts compare to this?

Starting to comment from the bottom: I have reviewed the Node.js article linked by the referee. Compared to that, astropy is actually significantly more restrictive. In Node.js anybody is given commit rights after their first non-trivial PR based on the observations that most PRs make the code better, most people know their limits and won't merge things they don't understand, and that in system (like astropy) where there are few committers per sub-package, the time those people have for reviews becomes a bottleneck. In git, if someone with commit rights messes up, there is always a way to recover, so the risk is low. That is a policy astropy might want to look into as well (@astropy/coordinators hint, hint ;-)  )

Otherwise, I think our approach to development is fairly standard across the open source world. We are more open (in term of how many people can make decisions) than the Linux kernel and less than Node.js. I don't think that what we do is a novelty, in the open source world, but it *is* a novelty in the astronomy software world. Maybe it is enough to just spell that out?

**Comment by bsipocz** [comment]
Both @eteq and especially @astrofrog defines it pretty nicely in their talks, but finding something in written is not that trivial. So far this blogpost seems to have some pretty useful thoughs, especially on the importance of communication and sharing. 
https://medium.com/adobe-io/open-development-vs-inner-source-fdccf573a242

**Comment by eteq** [comment]
I think the referee is starting from a different idea about what the phrase "open development" means than what we mean.  I think they think it's about who can "merge things", whereas to me it's more about who is involved in the *whole* process.  I.e., scientists sometimes write code  *and* review other code, all of it in the open.  So the first point is well taken that we need to define "open development".

I think I agree with @hamogu that this isn't necessarily particularly unusual in the open source context.  But the point I guess is that we do need to define it so that it's in the astro literature.  If you want to assign it to me I can take a shot at drafting this up. (As @bsipocz just pointed out as I finished writing this, I do this a lot in talks!)

> That is a policy astropy might want to look into as well 

I think the sociology is *very* different in these communities.  Node.js contributors are not astronomers, by and large.  Astronomers have a long history of basically being programmers without programming training.  Furthermore, to be blunt (although not naming names...), some have a much inflated sense of their own programming prowess and/or no sense that software is actually an engineering field with best practices. In their defense, it wasn't as true when some of them started... but there it is anyway.

Put another way, I think at least the current generation of astronomers do *not* "know their limits". ("current generation" meaning all current research astronomers - the "kids these days" I think *might* be on track to be better.)

**Comment by bsipocz** [comment]
yes, it's also quite amazing to see that soo many programming projects run by astronomers (not necessarily the ones who write the code) who still are not familiar with any software engineering principle that are already discussed in the 70s (e.g. in the mythical men-month), let alone what happened since. 

So it would be indeed useful to point out the differences.

**Comment by eteq** [comment]
A nice quote from the link  in https://github.com/astropy/astropy-v2.0-paper/issues/140#issuecomment-360520397 of relevance here: "We’re saying that the heart of Open Source is Open Development. It’s the way you collaborate."  That gets at the core idea: Open Source is about *where* the code *is*, Open Dev is about how the code is *built*.

**Comment by crawfordsm** [comment]
@hamogu can you take the lead on crafting something by 28 Feb?   You can either include your response to the referee in the comment to the PR or directly in the file response.txt.   It would be great to get a PR in before then in case it does need to be discussed further.

**Comment by hamogu** [comment]
I will address this issue.
