### ISSUE TITLE
Referee comment on Package development 

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#144]
```
 - A number of times I found myself wondering how the Astropy projects 
decides whether to build  their own package or leverage something available
in the scientific Python ecosystem? On the face of it it seems like every 
decision made by the Astropy project to build a new core package only 
increases the long term cost/overhead of maintaining this functionality. For 
example, Section 3.5.2 describes `astropy.table` and notes that there's 
similarities to the pandas package and numpy arrays. The functionality 
described in `astropy.nddata` also sounds somewhat generic. Some 
discussion as to why existing community tools (such as pandas) weren't used 
would be very welcome. In addition, if the answer to this question is that these 
other tools don't support all of the functionality the Astropy community needs 
(e.g. ability to handle Quantities with units in tables) are any efforts being made 
by the Astropy community to contribute these changes to packages such 
as Pandas? 

```

**Comment by eteq** [comment]
I see the referee's point that we should probably discuss this at least a bit in the paper.  Maybe something like:

* Astropy deeply intertwines with the existing Python scientific ecosystem.  Where possible we *always* try to use other tools instead of building our own. Some major astropy functionality is essentially an astro-relevant "wrapper" around existing code.  For example, modeling makes it easier to use fitting functions from `scipy` with various models that are primarily of interest in astronomy.
* Other bits of functionality are really astro-specific or the work to make it more "general" is difficult.  E.g. `coordinates` or `nddata` (which despite the general-sounding name, is focused on the needs of the astronomy community in things like choice of name and conventions for error propogation).
* Some other pieces were originally more astro-specific or had no equivalent *when they were started* and have grown more generalizable as time goes on - e.g. `units` and (to some extent) `table`.
* In general it's considered "best effort" to generalize because the first priority is basic tools for astro, dependent heavily on the time/interest of an individual to do the porting.  So for example some of the documentation and testing machinery is now (after v2.0) getting moved from astropy into a more generally-useful setting.  Meanwhile, `units`/`Quantity` would require a much larger effort to disentangle from astropy and maintain independently - absent a maintainer with enough time to do so, it fares better in the Astropy core.

This needs to be massaged into the paper itself somehow, but I think this is a good direction to go?

**Comment by eteq** [comment]
Also, I'm curious if the `table` team might have some words to say *specifically* on the final part of the  table/pandas thing?  My impression is that the answer is that some of the features important for `astropy.table` (e.g. mixin columns, `QTable`) couldn't go into pandas without major architectural changes that noone on the Pandas side would support, but @taldcroft or @mhvk might know better?

**Comment by crawfordsm** [comment]
@eteq can you craft a response to this by 28 Feb?   You can either include your response to the referee in the comment to the PR or directly in the file response.txt

**Comment by adrn** [comment]
@eteq: do you have time to work this in to the paper? If not, I can do it - just assign me.

**Comment by eteq** [comment]
28 Feb is doable. Will put in my calendar ;)

**Comment by hamogu** [comment]
I don't think all that @eteq listed above needs to go into the paper. I would just add the point of "we use whatever we can" and a few examples how we contribute back (the doc and testing tools) or upstream (units are lead to a lot of interaction with numpy as we seem to be the most heavy users of __array_finalize__ and friends). 
In my opinion, why we do tables independently and not into pandas is a more technical and specific reason. I would not discuss that in the paper, but just put it into the reply to the referee. My recollection is that pandas does not allow multi-D columns (which we need just to read fits files) and @taldcroft either asked the pandas developer or read over their history and discussion (I don't recall) and found that they have no interest in having such a feature in the first place.
