### ISSUE TITLE
citations in Fitting Models to Data

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-v2.0-paper#20]
@adrn  commented: 

Add citations to the fitters in Fitting Models to Data section of the paper

**Comment by nden** [comment]
@adrn What kind of citations do you think should be added? The section mentions the optimizers are implemented in scipy. Since we don't control this, in theory it can change depending on the version of scipy. I see two options - adding the names of the scipy functions used as optimizers or adding real citations to the papers describing the algorithms implemented in scipy, which are already in scipy, e.g. here

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin.html#scipy.optimize.fmin

My preference is to add the names of the scipy functions but I'm willing to go with citations if you think it's better.

**Comment by adrn** [comment]
Right, I think I was thinking for named algorithms like Levenberg-Marquardt, SLSQP, etc., since I think the algorithms have standard citations. But I'd be fine with switching to function names.
