### ISSUE TITLE
Appendix

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-v2.0-paper#85]
I noticed several issues in the Appendix in the draft I read:

* There is a giant blank area between Appendix section title and the tables.
* There are no paragraphs describing the tables in the Appendix. For example, we can explain why are the tables there.
* The affiliated package listing might not be up-to-date. Maybe the tables should be updated again after some PRs at https://github.com/astropy/astropy.github.com/pulls are merged? Or are we strictly listing only packages that were accepted when `astropy` 2.0 came out?

**Comment by hamogu** [comment]
I would not worry about the black space. The journal staff will reformat and typeset it for the journal anyway, so why should be waste our time to debug the latex? For most journals, it's sufficient to make a "good enough" layout, so that a) the referee can read it and b) you see that lay-outing is possible (e.g. no figures are bigger than one page).

An ApJ styple, every table in the appendix must be references in the main text, but no extra text in the appendix is required. Think of the appendix as "data only available in the electronic version" (that how it was used  in former times); typical examples would be something that's nice to have but not really required for the paper, e.g. finding charts for all your 150 objects in the paper, or plot of each and every spectrum of your sample of 345 galaxies, where in the main paper you only show one of each type. I think out tables fit that scheme with no further explanation.

**Comment by bsipocz** [comment]
@pllim - I think we need to list every package that is currently accepted as affiliated. Hopefully the @astropy/coordinators have a full and complete list that tracks the review stages.

**Comment by hamogu** [comment]
@astropy/coordinators : What is the most complete list of affiliated packages? The astropy website?

**Comment by adrn** [comment]
Closing this in favor of #146
